[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.2"

[[constraint]]
  branch = "master"
  name = "github.com/google/go-github"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"

[[constraint]]
  name = "github.com/julienschmidt/httprouter"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/kardianos/osext"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  name = "github.com/spf13/viper"
  branch = "master"

[[constraint]]
  name = "github.com/tendermint/abci"
  version = "0.7.1"

[[constraint]]
  branch = "master"
  name = "github.com/tendermint/merkleeyes"

[[constraint]]
  name = "github.com/tendermint/go-wire"
  version = "0.7.1"

[[constraint]]
  name = "github.com/tendermint/tendermint"
  version = "0.12.0"

[[constraint]]
  name = "github.com/tendermint/tmlibs"
  version = "0.4.0"

[[constraint]]
  branch = "master"
  name = "github.com/xeipuuv/gojsonschema"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"
