[[constraint]]
  name = "github.com/tendermint/go-wire"
  source = "github.com/tendermint/go-amino"
  version = "~0.7.3"

[[constraint]]
  name = "github.com/tendermint/tendermint"
  version = "0.18.0"

[[constraint]]
  branch = "master"
  name = "github.com/xeipuuv/gojsonschema"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  name = "github.com/golang/mock"
  branch="master"
  
[[constraint]]
  name = "github.com/google/go-querystring"
  branch="master"

[[constraint]]
  name = "github.com/jmespath/go-jmespath"
  branch="master"

[[override]] 
  # This is required because Tendermint needs ~1.0.0
  # but Docker claims it needs ^0.4.
  name = "github.com/gogo/protobuf"
  version = "~1.0.0"

[[constraint]]
  name = "github.com/stratumn/go-crypto"
  branch = "master"

[[override]]
  name = "github.com/chzyer/readline"
  branch = "fix-bell"
  source = "github.com/stratumn/readline"

[[constraint]]
  name = "go.opencensus.io"
  branch = "master"
